# Generated by Django 6.1 on 2026-08-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_realtor_property_realtor'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_published', '-created_at'], name='property_pub_created_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['featured', 'is_published'], name='property_feat_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='property_type_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['listing_type'], name='property_listing_type_idx'),
        ),
    ]
