# Generated by Django 6.1 on 2026-08-24 23:16

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_property_property_pub_created_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', validators=[pages.models.validate_image_file_size]),
        ),
    ]
