# Generated by Django 6.1 on 2026-08-25 20:47

import django.db.models.deletion
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_realtor_photo_inquiry_inquiry_status_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', validators=[pages.models.validate_image_file_size])),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.property')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
