# Generated by Django 6.1 on 2026-08-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_propertyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'ordering': ['user__username']},
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='One amenity per line, e.g. Swimming pool, 24/7 security, Gym'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
