# Generated by Django 6.1 on 2026-09-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_property_is_verified_property_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='pages.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'viewer_key'), name='unique_property_viewer')],
            },
        ),
    ]
